### ISSUE TITLE
プレーヤー動けなくなる場所が出てくるときがある

### ISSUE THREAD

**Issue by nekosuke1** [morinoparty/MinecraftServer#10]
クリーパーの爆発などでできた空間などに何故か動けなくなる場所が出てくるときがある
頑張れば脱出可能
https://www.youtube.com/watch?v=ZpdLuvDMsNs

**Comment by NamiUni** [comment]
所謂ゴーストブロックと呼ばれる現象で、サーバーにはブロックが存在しているがクライアント側ではブロックが表示されていない時に発生する。
バニラにも存在するバグで高速採掘などを行うと発生しやすい。
f3+aのチャンク再読み込みで直るかも？

今回の現象は恐らくpaperのバグだと思われる

**Comment by NamiUni** [comment]
たぶん直ってる
