### ISSUE TITLE
サーバー参加時に<name>が参加しましたがログに出なくなっている

### ISSUE THREAD

**Issue by nekosuke1** [morinoparty/MinecraftServer#11]
サーバー参加時に<name>が参加しましたがログに出なくなっている
退出時は問題なくログに出る

**Comment by nekosuke1** [comment]
退出ログも機能しなくなった模様

**Comment by Nlkomaru** [comment]
https://github.com/Nlkomaru/NoticeConnect/releases/tag/v0.0.7

1.18.2に対応しました
プラグインも入れ替えました
