### ISSUE TITLE
ネームタグ消せる機能が欲しい

### ISSUE THREAD

**Issue by NamiUni** [morinoparty/MinecraftServer#19]
かくれんぼとかスクショとか色んなとこで使えそう

**Comment by Nlkomaru** [comment]
https://www.spigotmc.org/resources/no-name-tag.70128/
https://github.com/AuracleTech/NoNameTag

**Comment by NamiUni** [comment]
入れたら問答無用で全部消えたやんけ！

**Comment by NamiUni** [comment]
テキトーに自分で作った
https://github.com/morinoparty/Kakuremi
