### ISSUE TITLE
なぞのばしょに行けるバグ

### ISSUE THREAD

**Issue by NamiUni** [morinoparty/MinecraftServer#20]
1. 生活サーバーで死にます
2. リスポーンせずにタイトル画面に戻ります
3. サーバーに入り直します
4. 生活サーバーへ行かずに資源サーバーへ行きます
5. **なぜか死にます**
6. 生活サーバーへ行くとなぞのばしょへ行けます
7. チャットを打とうとする「クライアントの設定でチャットが無効になっています」と出ます

リログすれば直る模様。生活サーバーのログに以下のメッセージが残っていた
```Skipping update from removed player 'EntityPlayer['Unitarou'/108012, uuid='ebf3f7ae-6a77-4537-845b-6f0470a101b8', l='ServerLevel[world_nether]', x=0.50, y=68.00, z=0.50, cpos=[0, 0], tl=106671387, v=false, removed=KILLED](Unitarou at 0.5,68.0,0.5)'```

**Comment by NamiUni** [comment]
`/gamerule doImmediateRespawn true` で死亡画面をスキップしてとりあえず回避

**Comment by bakaneco-github** [comment]
これまだあるんかな

**Comment by NamiUni** [comment]
検証したらまだ残ってた

**Comment by NamiUni** [comment]
直ってた
