### ISSUE TITLE
鉄桑でエンダーチェストをクリックすると何故かエンダーチェストが開いたままになる

### ISSUE THREAD

**Issue by nekosuke1** [morinoparty/MinecraftServer#25]
チェストクリーナーのバグだと思われる
一定時間たつと閉じる模様

**Comment by NamiUni** [comment]
これサーバー側な気もするけど、クライアント側の問題な気もする。
どっちか判断つかない。

**Comment by NamiUni** [comment]
今日は再現が出来なかった。直ったかも？
どちらにせよ実害のないバグなので閉じます
